stages:
  ingest:
    cmd: python3 src/ingest.py data/ingest 
    deps:
    - src/ingest.py 
    outs:
    - data/ingest
    always_changed: true

  transform:
    cmd: python3 src/transform.py data/transform data/ingest
    deps:
    - src/transform.py
    - data/ingest
    outs:
    - data/transform
    always_changed: true

  split:
    cmd: python3 src/split.py data/split data/transform
    deps:
    - src/split.py
    - data/transform
    outs:
    - data/split
    always_changed: true

  train:
    cmd: python3 src/train.py data/train data/split
    deps:
    - src/train.py
    - data/split
    params:
    - yolov5.weights
    outs:
    - data/train
    always_changed : true 

  predict:
    cmd: python3 src/predict.py data/predict data/split
    deps:
    - src/predict.py
    - data/split
    params:
    - yolov5.weights
    outs:
    - data/predict
    always_changed : true 

  compare:
    cmd: python3 src/compare.py data/compare data/train data/predict
    deps:
    - src/compare.py
    - data/train
    - data/predict
    params:
    - yolov5.count
    outs:
    - data/compare
    always_changed : true 